spring:
  application:
    name: eureka-server
#server:
#  port: 2001
#
eureka:
  server:
    enable-self-preservation: false   #关闭自我保护，服务连接失败删除注册信息，开发过程关闭，上线时开启
#  instance:
#    hostname: eureka1
#  client:
#    register-with-eureka: false   #不向自身注册
#    fetch-registry: false   #不从自身拉去注册信息
#    service-url:
#      defaultZone: http://eureka1:2002/eureka   #防止eureka报8761端口连接超时，默认注册中心配置地址http://localhost:8761/eureka/,单台eureka才会出先问题，多台不会，这是相互注册

---
spring:
  profiles: eureka1

server:
  port: 2001
#eureka1向eureka2注册
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:2002/eureka

---
spring:
  profiles: eureka2

server:
  port: 2002
#eureka2向eureka1注册
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka