spring:
  application:
    name: order-service
  #控制中心配置会覆盖客户端配置，需禁止
  cloud:
    config:
      override-none: true
#server:
#  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#暴漏端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
#ribbon超时设置，全局配置
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
#ribbon配置，某个微服务
item-service:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    ConnectTimeout: 1000
    ReadTimeout: 500
#启用hystrix
feign:
  hystrix:
    enabled: true
#hystrix超时配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
#order集群
---
spring:
     profiles: order1

server:
  port: 8201

---
spring:
  profiles: order2

server:
  port: 8202
